### ISSUE TITLE
Payload not being null-terminated

### ISSUE THREAD

**Issue by Shdwdrgn** [marvinroger/async-mqtt-client#35]
I am using an ESP8266-12F and the Arduino IDE 1.6.12.  I installed the latest master on November 30th, but I have been having problems with the payload.  Starting with FullyFeatured.ino and entering my wifi info, I also added the following lines to the end of onMqttMessage (after line 58):
`  Serial.print("  payload: '");
  Serial.print(payload);
  Serial.println("'");

  char new_payload[len+1];
  new_payload[len] = '\0';
  strncpy(new_payload, payload, len);
  Serial.print("**new_payload: '");
  Serial.print(new_payload);
  Serial.println("'");`

Following is an example of the types of results I am seeing:
`** Publish received **
  topic: test/lol
  qos: 0
  dup: 0
  retain: 0
  len: 6
  index: 0
  total: 6
  payload: 'test 1@'
**new_payload: 'test 1'

** Publish received **
  topic: test/lol
  qos: 1
  dup: 0
  retain: 0
  len: 6
  index: 0
  total: 6
  payload: 'test 2P'
**new_payload: 'test 2'

** Publish received **
  topic: test/lol
  qos: 2
  dup: 0
  retain: 0
  len: 6
  index: 0
  total: 6
  payload: 'test 3	'
**new_payload: 'test 3'`

Note that payload always has extra characters at the end and is not properly null-terminated.  When I create a new char and set the last byte to null, the payload is correctly displayed.  Trying to work directly with payload is impossible, whether storing it as a string or trying to convert it with atoi(), however all operations with new_payload appear to be working.

Attempting to fix payload directly with this line causes immediate resets:
`payload[len] = '\0';`

This has been tested on two different ESP8266-12F boards to ensure it wasn't a hardware fault, and the value of len always matches the exact data I'm trying to send.

**Comment by marvinroger** [comment]
The char array you're getting in the callback is the raw buffer from the TCP stack, it's not an internal buffer, so we basically don't have any control over it (we can't add +1 to the buffer length to add the null terminator). We can't add `\0` to the `payload[len]` because the memory there is not allocated for us, so it crashes.

The solution would be to copy the TCP window (which is about 1kb) into an internal buffer (+1 in length), but I am pretty sure you agree that this is a waste of memory, only to add a null terminator. I prefer this library to stay low-level, so this kind of manipulation should be done in higher level code.
