### ISSUE TITLE
connect/disconnect cycle with FullyFeaturedSSL example

### ISSUE THREAD

**Issue by chessweb01** [marvinroger/async-mqtt-client#54]
I'm trying the FullyFeaturedSSL example. It works with nossl, but when I try the code with ssl I run into the connect/disconnect cycle. The disconnect reason is 0. What could be the TCP problem considering that nossl works?

**Comment by umitech** [comment]
The same problem here. 

I did some investigation on the source and I guess that the problem comes from the AsyncTCP library or at least the way of using that.

Can some one help about this?

**Comment by umitech** [comment]
After some digging in the codes, I found that it works if we send our packets with some delay. 

It seems that it gets disconnected when we send some packets at a small time. I guess that the problem comes from the fact that the encryption in SSL is time consuming and the processor can't handle that much of packets (around 6 packets with average 100 bytes in size (including topic and the payload)).

The workaround for me was to queue the packets and send them one by one with some delay between them. Not a nice approach but at least it works now.

I hope it helps some one who has the same problem and also I hope some one can solve it with a better approach at the deeper levels.

**Comment by bertmelis** [comment]
I'm running a ESP8266 with SSL using the develop branch as we speak. Feel free to reopen if the issue persists.

**Comment by jeroenst** [comment]
Related to this?
https://github.com/marvinroger/async-mqtt-client/issues/107
